// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AIService is an autogenerated mock type for the AIService type
type AIService struct {
	mock.Mock
}

// GenerateHint provides a mock function with given fields: content
func (_m *AIService) GenerateHint(content string) (string, error) {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for GenerateHint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(content)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIService creates a new instance of AIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIService {
	mock := &AIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
