// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/philipos/prepbase/domain"
	mock "github.com/stretchr/testify/mock"
)

// CommentUsecase is an autogenerated mock type for the CommentUsecase type
type CommentUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: comment
func (_m *CommentUsecase) Create(comment *domain.Comment) error {
	ret := _m.Called(comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Comment) error); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, authorID, userRole
func (_m *CommentUsecase) Delete(id string, authorID string, userRole string) error {
	ret := _m.Called(id, authorID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, authorID, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByQuestionID provides a mock function with given fields: questionID
func (_m *CommentUsecase) GetByQuestionID(questionID string) ([]domain.Comment, error) {
	ret := _m.Called(questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByQuestionID")
	}

	var r0 []domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Comment, error)); ok {
		return rf(questionID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Comment); ok {
		r0 = rf(questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, authorID, content
func (_m *CommentUsecase) Update(id string, authorID string, content string) error {
	ret := _m.Called(id, authorID, content)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, authorID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommentUsecase creates a new instance of CommentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentUsecase {
	mock := &CommentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
