// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/philipos/prepbase/domain"
	mock "github.com/stretchr/testify/mock"
)

// QuestionUsecase is an autogenerated mock type for the QuestionUsecase type
type QuestionUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: question
func (_m *QuestionUsecase) Create(question *domain.Question) error {
	ret := _m.Called(question)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Question) error); ok {
		r0 = rf(question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, authorID, userRole
func (_m *QuestionUsecase) Delete(id string, authorID string, userRole string) error {
	ret := _m.Called(id, authorID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, authorID, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Downvote provides a mock function with given fields: userID, questionID
func (_m *QuestionUsecase) Downvote(userID string, questionID string) error {
	ret := _m.Called(userID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for Downvote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAll provides a mock function with given fields: cursor, limit
func (_m *QuestionUsecase) FetchAll(cursor string, limit int) ([]domain.Question, error) {
	ret := _m.Called(cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]domain.Question, error)); ok {
		return rf(cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []domain.Question); ok {
		r0 = rf(cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateAIHint provides a mock function with given fields: id
func (_m *QuestionUsecase) GenerateAIHint(id string) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAIHint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *QuestionUsecase) GetByID(id string) (*domain.Question, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Question, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Question); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, authorID, question
func (_m *QuestionUsecase) Update(id string, authorID string, question *domain.Question) error {
	ret := _m.Called(id, authorID, question)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *domain.Question) error); ok {
		r0 = rf(id, authorID, question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upvote provides a mock function with given fields: userID, questionID
func (_m *QuestionUsecase) Upvote(userID string, questionID string) error {
	ret := _m.Called(userID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for Upvote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestionUsecase creates a new instance of QuestionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionUsecase {
	mock := &QuestionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
