// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/philipos/prepbase/domain"
	mock "github.com/stretchr/testify/mock"
)

// QuestionRepository is an autogenerated mock type for the QuestionRepository type
type QuestionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: question
func (_m *QuestionRepository) Create(question *domain.Question) error {
	ret := _m.Called(question)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Question) error); ok {
		r0 = rf(question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *QuestionRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAll provides a mock function with given fields: cursor, limit
func (_m *QuestionRepository) FetchAll(cursor string, limit int) ([]domain.Question, error) {
	ret := _m.Called(cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]domain.Question, error)); ok {
		return rf(cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []domain.Question); ok {
		r0 = rf(cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *QuestionRepository) GetByID(id string) (*domain.Question, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Question, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Question); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementViews provides a mock function with given fields: id
func (_m *QuestionRepository) IncrementViews(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: question
func (_m *QuestionRepository) Update(question *domain.Question) error {
	ret := _m.Called(question)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Question) error); ok {
		r0 = rf(question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVoteCount provides a mock function with given fields: questionID, upvoteChange, downvoteChange
func (_m *QuestionRepository) UpdateVoteCount(questionID string, upvoteChange int, downvoteChange int) error {
	ret := _m.Called(questionID, upvoteChange, downvoteChange)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVoteCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = rf(questionID, upvoteChange, downvoteChange)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuestionRepository creates a new instance of QuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionRepository {
	mock := &QuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
