// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/philipos/prepbase/domain"
	mock "github.com/stretchr/testify/mock"
)

// VoteRepository is an autogenerated mock type for the VoteRepository type
type VoteRepository struct {
	mock.Mock
}

// AddVote provides a mock function with given fields: vote
func (_m *VoteRepository) AddVote(vote *domain.Vote) error {
	ret := _m.Called(vote)

	if len(ret) == 0 {
		panic("no return value specified for AddVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Vote) error); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteVote provides a mock function with given fields: userID, questionID
func (_m *VoteRepository) DeleteVote(userID string, questionID string) error {
	ret := _m.Called(userID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetVote provides a mock function with given fields: userID, questionID
func (_m *VoteRepository) GetVote(userID string, questionID string) (*domain.Vote, error) {
	ret := _m.Called(userID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetVote")
	}

	var r0 *domain.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.Vote, error)); ok {
		return rf(userID, questionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.Vote); ok {
		r0 = rf(userID, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVote provides a mock function with given fields: vote
func (_m *VoteRepository) UpdateVote(vote *domain.Vote) error {
	ret := _m.Called(vote)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Vote) error); ok {
		r0 = rf(vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVoteRepository creates a new instance of VoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteRepository {
	mock := &VoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
